### PR TITLE
media-sound/deadbeef: fix compile with gcc-8 for arm

### PR DESCRIPTION
**Pull request by stefson**
The build fails on arm with gcc-8, it creates these three beauties: 

(all patches are backports from upstream, opting for -r3 to allow easier backwards comp. testing)

```
make[2]: Entering directory '/tmp/deadbeef-0.7.2/plugins/adplug'
  CXX    s3m.lo
  CXX    sa2.lo
  CXX    sng.lo
  CXX    surroundopl.lo
adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
 {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,1,2,3,4,5,6,7,8,-1,-1,-1,-1,-1,-1,-1};
                                                                                        ^

adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
adplug/s3m.cpp:30:90: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
```

```
make[2]: Entering directory '/tmp/deadbeef-0.7.2/plugins/adplug'
  CXX    adplug.lo
  CXX    dmo.lo
  CXX    s3m.lo
  CXX    temuopl.lo
In file included from adplug/dmo.h:22,
                 from adplug/dmo.cpp:31:
adplug/s3m.h:95:16: error: 'int8_t' does not name a type; did you mean 'int'?
   static const int8_t chnresolv[];
                ^~~~~~
                int
In file included from adplug/s3m.cpp:27:
adplug/s3m.h:95:16: error: 'int8_t' does not name a type; did you mean 'int'?
   static const int8_t chnresolv[];
                ^~~~~~
                int
adplug/s3m.cpp:29:7: error: 'int8_t' does not name a type; did you mean 'int'?
 const int8_t Cs3mPlayer::chnresolv[] = // S3M -> adlib channel conversion
       ^~~~~~
       int
make[2]: *** [Makefile:892: dmo.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
adplug/s3m.cpp: In member function 'virtual bool Cs3mPlayer::update()':
adplug/s3m.cpp:259:18: error: 'chnresolv' was not declared in this scope
       realchan = chnresolv[header.chanset[chan] & 127];
                  ^~~~~~~~~

```  

```  
CXX    xsid.lo
  CXX    mos6526.lo
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\200'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
 };
 ^
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\224'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\251'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\274'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\316'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\341'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
sidplay-libs/libsidplay/src/xsid/xsid.cpp:88:1: error: narrowing conversion of ''\362'' from 'char' to 'int8_t' {aka 'signed char'} inside { } [-Wnarrowing]
make[2]: *** [Makefile:888: xsid.lo] Error 1
```

### CODE REVIEW

**Comment by damex** [comment]
Hi, could you please make it as a conditional to your arm architecture? is it arm64?

**Comment by stefson** [comment]
No, its for arm. I can do that, but maybe amd64 needs them as well? Which is why I opted for a -r3, fixes for compile errors normally don't need an additional -rX

**Comment by damex** [comment]
Yeah, that is fine for me, please make some testing for amd64.

**Comment by stefson** [comment]
Ok, amd64 doesn't need this for whatever reason. It can go! If someone with arm64 hits it too, they'll have to take actions themselves.

**Pull request merged**
